# Receiving data for Elasticsearch from the source

input {
  gelf {
    port => 12201
  }
}

filter {
  mutate {
    # Adding a custom field to identify our project logs
    add_field => { "source_system" => "NYC_Data_Pipeline" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
  
  # Print to Logstash console for debugging
  stdout { 
    codec => rubydebug 
  }
}